// Regenerate demo/index.html from the CURRENT index.html by applying the DEMO LAYER.
//
// The demo is the FULL game (single source of truth = index.html) with an ADDITIVE overlay:
//   • a Case Select front-end (4 fixed, hand-picked cases — no random/daily/load-by-code),
//   • Steam / socials / Kickstarter call-to-action moments on the win payoff,
//   • a "Demo Complete" finale once all four are solved,
//   • the Manor home hub is GATED (hidden via body.demo CSS) rather than removed, so there is no
//     coupling to maintain — entry/return buttons are re-bound to Case Select.
//   • a <base href="../"> so demo/index.html (which lives in /demo) resolves the repo-root assets/.
//
// This keeps the demo's logic byte-for-byte in sync with the main game (the engine + every fix flows
// straight through). To re-sync after ANY game change: `npm run build:demo`.
//
// The script keys off stable strings already in index.html (no markers added to the source):
//   <head>, the main </style></head>, <body>, the win-modal payoff-actions, the #cludoku-ui IIFE
//   close (`if(DEV_ON) buildDevPanel();\n})();`), and </body>. Each is asserted before writing.

import { readFileSync, writeFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
let html = readFileSync(join(root, 'index.html'), 'utf8');
const orig = html;

const fail = (m) => { throw new Error('[build-demo] ' + m); };
function apply(label, find, replace) {
  if (typeof find === 'string') {
    if (!html.includes(find)) fail('anchor NOT found for "' + label + '" — index.html structure changed; update build-demo.mjs');
    html = html.replace(find, replace);
  } else {
    if (!find.test(html)) fail('anchor NOT found for "' + label + '" — index.html structure changed; update build-demo.mjs');
    html = html.replace(find, replace);
  }
}

/* ---- 1) <base href="../"> so /demo/index.html resolves repo-root assets/ (all paths stay "assets/...") ---- */
apply('base-href', '<head>', '<head>\n  <base href="../"><!-- DEMO: resolve repo-root assets/ from /demo/ -->');

/* ---- 2) mark the body so the demo CSS can gate the manor home ---- */
apply('body-class', /<body>/, '<body class="demo">');

/* ---- 3) DEMO CSS (Case Select, CTA, Demo Complete, demo badge) + the manor gate, before </style></head> ---- */
const DEMO_CSS = `
  /* ===================== DEMO BUILD additions (generated by scripts/build-demo.mjs) ===================== */
  /* gate the Manor home hub: the demo enters through Case Select, so the manor screen + its boot story never show */
  body.demo #manorScreen{display:none !important;}
  /* small DEMO badge near the header */
  .demo-badge{display:inline-flex;align-items:center;gap:5px;align-self:center;
    font-family:"Courier New",monospace;font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;
    color:var(--amber-soft);background:rgba(231,185,77,.10);border:1px solid rgba(231,185,77,.5);
    padding:3px 8px;border-radius:6px;box-shadow:0 1px 4px rgba(0,0,0,.5);}
  /* ---- Case Select screen (the demo's only entry to a case) ---- */
  .case-select{position:fixed;inset:0;z-index:70;overflow-y:auto;
    background:linear-gradient(rgba(8,9,13,.86),rgba(8,9,13,.95)),url("assets/ui/bg-desktop.jpg");
    background-size:cover;background-position:center;
    display:flex;flex-direction:column;align-items:center;padding:40px 18px 60px;}
  .case-select[hidden]{display:none;}
  .cs-logo{height:74px;filter:drop-shadow(0 2px 6px rgba(0,0,0,.6));margin-bottom:6px;}
  .cs-logo[hidden]{display:none;}
  .cs-wordmark{font-family:Georgia,serif;font-weight:bold;font-size:34px;color:var(--amber-soft);letter-spacing:3px;}
  .cs-wordmark[hidden]{display:none;}
  .cs-title{font-family:"Courier New",monospace;letter-spacing:4px;text-transform:uppercase;color:var(--ink-dim);
    font-size:13px;margin:6px 0 2px;}
  .cs-tagline{color:var(--ink);font-style:italic;font-size:15px;max-width:560px;text-align:center;margin:4px 0 22px;line-height:1.5;}
  .cs-tagline b{color:var(--amber-soft);font-style:normal;}
  .cs-grid{display:grid;grid-template-columns:repeat(2,minmax(240px,310px));gap:18px;width:100%;max-width:680px;}
  .cs-card{position:relative;text-align:left;cursor:pointer;color:var(--ink);
    background:linear-gradient(180deg,#1c1f29,#15171f);border:1px solid var(--line);border-radius:12px;
    padding:18px 18px 16px;box-shadow:0 14px 40px rgba(0,0,0,.55);transition:.14s;overflow:hidden;font-family:inherit;}
  .cs-card:hover{border-color:var(--amber);transform:translateY(-3px);box-shadow:0 18px 48px rgba(0,0,0,.6);}
  .cs-card::before{content:"CASE FILE";position:absolute;top:12px;right:-8px;transform:rotate(8deg);
    border:2px solid rgba(193,39,45,.5);color:rgba(193,39,45,.65);font-family:"Courier New",monospace;
    font-weight:700;font-size:9px;padding:2px 7px;letter-spacing:1px;border-radius:3px;}
  .cs-card-head{display:flex;align-items:center;gap:10px;margin-bottom:8px;}
  .cs-badge{width:34px;height:34px;flex:none;filter:drop-shadow(0 1px 3px rgba(0,0,0,.6));}
  .cs-badge.img-missing{display:none;}
  .cs-flavor{font-size:19px;color:var(--blood);font-variant:small-caps;letter-spacing:1px;line-height:1.1;}
  .cs-size{display:block;font-family:"Courier New",monospace;font-size:10px;letter-spacing:1.5px;
    text-transform:uppercase;color:var(--ink-dim);margin-top:2px;}
  .cs-desc{font-size:13.5px;line-height:1.5;color:var(--ink);min-height:40px;}
  .cs-foot{display:flex;align-items:center;justify-content:space-between;margin-top:12px;
    border-top:1px dashed var(--line);padding-top:9px;font-family:"Courier New",monospace;font-size:11px;letter-spacing:1px;}
  .cs-no{color:var(--ink-dim);}
  .cs-open{color:var(--amber-soft);}
  .cs-card.done{border-color:rgba(76,175,125,.55);}
  .cs-stamp{position:absolute;bottom:10px;right:12px;transform:rotate(-9deg);
    font-family:"Courier New",monospace;font-weight:700;font-size:13px;letter-spacing:1px;
    color:var(--good);border:2px solid var(--good);border-radius:5px;padding:2px 8px;opacity:.92;display:none;}
  .cs-card.done .cs-stamp{display:block;}
  .cs-card.done .cs-open{visibility:hidden;}
  .cs-progress{margin:18px 0 0;font-family:"Courier New",monospace;font-size:12px;letter-spacing:1.5px;color:var(--ink-dim);}
  .cs-progress b{color:var(--amber-soft);}
  .cs-allclear{margin-top:14px;}
  /* ---- demo call-to-action block (win payoff + Demo Complete) ---- */
  .demo-cta{margin:12px 0 4px;border-top:1px dashed var(--line);padding-top:12px;}
  .demo-cta:empty{display:none;}
  .demo-cta-lead{font-size:13.5px;color:var(--ink);font-style:italic;margin:0 0 9px;}
  .demo-cta-lead b{color:var(--amber-soft);font-style:normal;}
  .demo-cta-actions{display:flex;gap:9px;justify-content:center;flex-wrap:wrap;}
  .cta-btn{display:inline-flex;align-items:center;gap:7px;cursor:pointer;font-family:inherit;font-size:13.5px;font-weight:700;
    border-radius:9px;padding:10px 14px;border:1px solid var(--line);color:var(--ink);
    background:linear-gradient(180deg,#262b38,#1b1f2a);transition:.12s;}
  .cta-btn:hover{transform:translateY(-2px);}
  .cta-btn .cta-ico{font-size:16px;line-height:1;}
  .cta-steam{border-color:#66c0f4;color:#cfeaff;background:linear-gradient(180deg,#1b3346,#12222e);}
  .cta-steam:hover{box-shadow:0 6px 18px rgba(102,192,244,.3);border-color:#9fd6ff;}
  .cta-kick{border-color:#05ce78;color:#bff7dc;background:linear-gradient(180deg,#123a2a,#0d271d);}
  .cta-kick:hover{box-shadow:0 6px 18px rgba(5,206,120,.28);border-color:#3ee79b;}
  .cta-social{border-color:var(--amber);color:var(--amber-soft);background:linear-gradient(180deg,#3a2f14,#251d0d);}
  .cta-social:hover{box-shadow:0 6px 18px rgba(231,185,77,.28);}
  /* ---- "Demo Complete" finale modal ---- */
  .demo-done-art{font-size:46px;margin:2px 0 0;}
  #demoCompleteModal h2{font-size:30px;color:var(--amber-soft);}
  .demo-done-sub{color:var(--ink);font-size:15px;line-height:1.55;margin:6px auto 4px;max-width:440px;}
  .demo-done-sub b{color:var(--amber-soft);}
`;
apply('demo-css', /<\/style>(\s*<\/head>)/, DEMO_CSS + '</style>$1');

/* ---- 4) winCta container inside the win payoff (before the action buttons) ---- */
apply('win-cta',
  '<div class="payoff-actions">\n        <button class="btn" id="winArchive"',
  '<div class="demo-cta" id="winCta"></div>\n      <div class="payoff-actions">\n        <button class="btn" id="winArchive"');

/* ---- 5) DEMO HTML (Case Select + Demo Complete) before </body> ---- */
const DEMO_HTML = `
  <!-- ===== DEMO: Case Select — the only way into a case (4 fixed cases) ===== -->
  <div class="case-select" id="caseSelect" hidden>
    <img class="cs-logo" id="csLogo" alt="Casedoku" hidden />
    <div class="cs-wordmark" id="csWordmark" hidden>CASEDOKU</div>
    <div class="cs-title">Casedoku — Demo · Blackwood Manor</div>
    <p class="cs-tagline">A sudoku you finish with detective work. <b>Four hand-picked cases</b>, one of each difficulty — place the suspects, weigh the evidence, and name the killer.</p>
    <div class="cs-grid" id="csGrid"></div>
    <div class="cs-progress" id="csProgress"></div>
    <button class="btn primary cs-allclear" id="csHowto" style="margin-top:14px">How to play</button>
  </div>
  <!-- ===== DEMO: finale shown once all 4 cases are solved ===== -->
  <div class="modal-bg" id="demoCompleteModal">
    <div class="modal center">
      <button class="x" id="demoCompleteClose"><img src="assets/ui/icon-close.png" alt="close"/></button>
      <div class="demo-done-art">\u{1F575}️‍♂️\u{1F3C6}</div>
      <h2>Demo Complete</h2>
      <p class="demo-done-sub">You cracked all <b>four</b> cases of the Casedoku demo. The full game has <b>endless procedural mysteries</b>, more themes, weapons, and culprits to unmask.</p>
      <div class="demo-cta" id="demoCompleteCta"></div>
      <button class="btn" id="demoCompleteBack" style="margin-top:14px"><img src="assets/ui/icon-back.png" alt=""/>Back to the case files</button>
    </div>
  </div>
`;
apply('demo-html', '</body>', DEMO_HTML + '</body>');

/* ---- 6) DEMO JS injected at the END of the #cludoku-ui IIFE (so it shares scope: $, LS, E, startCase, …) ---- */
const DEMO_JS = `
/* ===== DEMO LAYER (generated by scripts/build-demo.mjs — do NOT hand-edit demo/index.html) =====
   Case Select front-end over the full game: 4 fixed cases + Steam/Kickstarter/socials CTAs + a
   Demo Complete finale. The Manor home is gated (hidden) via body.demo CSS; entry/return route here. */
window.DEMO_LINKS = window.DEMO_LINKS || { STEAM_URL:"#", KICKSTARTER_URL:"#", SOCIALS:"#" };
const DEMO_CASES=[
  {key:"easy",    seed:135, desc:"A gentle 6x6 warm-up — learn how the evidence and the grid crack each other open."},
  {key:"medium",  seed:156, desc:"The full 9x9 manor: a balanced spread of every kind of clue. The classic whodunit."},
  {key:"hard",    seed:99,  desc:"A knotted 9x9 — and the weapon found by the body may well have been planted."},
  {key:"extreme", seed:119, desc:"The coldest case: barely any givens, so only the evidence can name the killer."},
];
const DEMO_DONE_KEY="demoDone";
function demoDone(){ return LS.get(DEMO_DONE_KEY,{})||{}; }
function isDoneKey(k){ return !!demoDone()[k]; }
function markDone(k){ const d=demoDone(); d[k]=true; LS.set(DEMO_DONE_KEY,d); }
function allDone(){ return DEMO_CASES.every(c=>isDoneKey(c.key)); }
function demoCaseNo(seed){ return 100+(seed%900); }
let activeDemoKey=null;
function hideCaseSelect(){ const cs=$("caseSelect"); if(cs) cs.hidden=true; }
function showCaseSelect(){ renderCaseSelect(); const cs=$("caseSelect"); if(cs) cs.hidden=false; }
function launchDemoCase(c){ activeDemoKey=c.key; hideCaseSelect(); startCase({difficulty:c.key, seed:c.seed}); }
function renderCaseSelect(){
  const grid=$("csGrid"); if(!grid) return; grid.innerHTML="";
  DEMO_CASES.forEach(c=>{
    const N=E.TIERS[c.key].cfg.N, size=N+"x"+N, done=isDoneKey(c.key);
    const card=document.createElement("button"); card.className="cs-card"+(done?" done":"");
    card.innerHTML='<div class="cs-card-head"><img class="cs-badge img-missing" alt=""><div><span class="cs-flavor">'+TIER_FLAVOR[c.key]+'</span><span class="cs-size">'+size+' grid</span></div></div><div class="cs-desc">'+c.desc+'</div><div class="cs-foot"><span class="cs-no">Case No. '+demoCaseNo(c.seed)+'</span><span class="cs-open">Open file \\u25B8</span></div><span class="cs-stamp">\\u2713 Solved</span>';
    card.onclick=()=>launchDemoCase(c); grid.appendChild(card);
    if(typeof loadOptionalImg==="function") loadOptionalImg(card.querySelector(".cs-badge"), "assets/ui/badge-"+c.key+".png");
  });
  const n=DEMO_CASES.filter(c=>isDoneKey(c.key)).length, prog=$("csProgress");
  if(prog) prog.innerHTML = allDone() ? "<b>All four cases solved.</b> Thank you for playing the Casedoku demo." : "Cases solved: <b>"+n+"</b> / "+DEMO_CASES.length;
}
function demoLink(which,btn){ const L=window.DEMO_LINKS||{}; const url=which==="steam"?L.STEAM_URL:which==="kick"?L.KICKSTARTER_URL:L.SOCIALS;
  if(url&&url!=="#"){ try{ window.open(url,"_blank","noopener"); }catch(e){ location.href=url; } return; }
  if(btn){ const o=btn.innerHTML; btn.innerHTML='<span class="cta-ico">\\u23F3</span> Link coming soon'; setTimeout(()=>{ btn.innerHTML=o; },1400); } }
function ctaHtml(){ return '<p class="demo-cta-lead">Enjoying the demo? <b>Support Casedoku</b> and follow the full game.</p><div class="demo-cta-actions"><button class="cta-btn cta-steam" data-cta="steam"><span class="cta-ico">\\u{1F3AE}</span> Wishlist on Steam</button><button class="cta-btn cta-social" data-cta="social"><span class="cta-ico">\\u2605</span> Visit our socials</button><button class="cta-btn cta-kick" data-cta="kick"><span class="cta-ico">\\u{1F680}</span> Back us on Kickstarter</button></div>'; }
function fillCta(c,show){ if(!c) return; if(show){ c.innerHTML=ctaHtml(); c.querySelectorAll("[data-cta]").forEach(b=>b.onclick=()=>demoLink(b.dataset.cta,b)); c.style.display=""; } else { c.innerHTML=""; c.style.display="none"; } }
function showDemoComplete(){ fillCta($("demoCompleteCta"),true); const m=$("demoCompleteModal"); if(m) m.classList.add("show"); }
function onDemoPayoff(won){ if(won&&activeDemoKey) markDone(activeDemoKey); fillCta($("winCta"),!!won); }
/* The #cludoku-ui IIFE runs DURING parse — the demo's Case Select / Demo Complete markup (injected just
   before </body>) isn't in the DOM yet, so all DOM wiring + the entry are deferred to DOMContentLoaded. */
function _demoReady(){
  /* re-bind entry / win / manor-exit controls to Case Select (manor home is hidden via body.demo) */
  if($("newBtn")) $("newBtn").onclick=()=>showCaseSelect();
  if($("manorNew")) $("manorNew").onclick=()=>showCaseSelect();
  if($("manorContinue")) $("manorContinue").onclick=()=>{ if(C&&!solved) hideCaseSelect(); else showCaseSelect(); };
  if($("escapeManor")) $("escapeManor").onclick=()=>{ const em=$("escapeModal"); if(em) em.classList.remove("show"); showCaseSelect(); };
  if($("winNew")) $("winNew").onclick=()=>{ $("winModal").classList.remove("show"); if(allDone()) showDemoComplete(); else showCaseSelect(); };
  if($("demoCompleteClose")) $("demoCompleteClose").onclick=()=>{ $("demoCompleteModal").classList.remove("show"); showCaseSelect(); };
  if($("demoCompleteBack")) $("demoCompleteBack").onclick=()=>{ $("demoCompleteModal").classList.remove("show"); showCaseSelect(); };
  if($("csHowto")) $("csHowto").onclick=()=>{ if(typeof openHowto==="function") openHowto(); else { const h=$("howtoModal"); if(h) h.classList.add("show"); } };
  /* when the win payoff appears, mark the fixed case done + show the CTA + relabel the return button */
  const wm=$("winModal");
  if(wm){ let handled=false;
    new MutationObserver(()=>{ const on=wm.classList.contains("show");
      if(on&&!handled){ handled=true; onDemoPayoff(true); const b=$("winNew"); if(b) b.innerHTML='<img src="assets/ui/icon-back.png" alt=""> Back to Cases'; }
      else if(!on){ handled=false; } }).observe(wm,{attributes:true,attributeFilter:["class"]}); }
  /* Case Select brand logo (probe ui logo, fall back to the wordmark) */
  (function(){ const logo=$("csLogo"), word=$("csWordmark");
    const show=src=>{ if(logo){ logo.src=src; logo.hidden=false; } if(word) word.hidden=true; };
    const fl=()=>{ if(logo) logo.hidden=true; if(word) word.hidden=false; };
    const probe=(src,next)=>{ const t=new Image(); t.onload=()=>show(src); t.onerror=next; t.src=src; };
    probe("assets/ui/logo-subtitle.png", ()=>probe("assets/ui/logo.png", fl)); })();
  /* ENTRY: gate the manor home, close any boot modal (opening story / mode choice), show Case Select */
  if(typeof hideManor==="function") hideManor();
  document.querySelectorAll(".modal-bg.show").forEach(m=>m.classList.remove("show"));
  showCaseSelect();
}
if(document.readyState==="loading") document.addEventListener("DOMContentLoaded", _demoReady); else _demoReady();
`;
apply('demo-js', 'if(DEV_ON) buildDevPanel();\n})();', 'if(DEV_ON) buildDevPanel();\n' + DEMO_JS + '\n})();');

/* ---- sanity: the demo MUST carry the current fixes + its own demo bits ---- */
const must = ['<base href="../">', 'class="demo"', 'id="caseSelect"', 'DEMO_CASES', 'id="winCta"',
  'translateY(-90px)' /* folder slides down */];
const mustNot = ['id="phasePill"', 'id="modePill"' /* chips removed */];
for (const m of must)    if (!html.includes(m)) fail('output missing required marker: ' + m);
for (const m of mustNot) if (html.includes(m))  fail('output still contains removed marker: ' + m);
if (html === orig) fail('no transforms applied');

writeFileSync(join(root, 'demo', 'index.html'), html);
console.log('[build-demo] demo/index.html regenerated — ' + statSync(join(root,'demo','index.html')).size + ' bytes (from index.html ' + orig.length + ' bytes)');
