// Authoring helper: generate the 3 detective-case grids at HARD difficulty (genuinely
// needs pencil-marking — hidden singles + locked candidates — yet fully logic-solvable,
// never a guess), and WRITE tools/cases.grids.mjs. The case prose (tools/cases.data.mjs)
// imports the grids from there, so regenerating never touches the writing.
//
// Uniqueness, culprit-at-labeled-cell, and decoy-to-non-culprit are all preserved by
// buildCaseGrid and re-proven by tools/verify-cases.mjs.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { DIMS9, buildCaseGrid, boxOf, hasUniqueSolution, rateDifficulty } from './sudoku.mjs';

const N = 9;
const rc = (i) => `r${(i / N) | 0}c${i % N} (box ${boxOf(DIMS9, (i / N) | 0, i % N)})`;

// Each labeled box carries an id (matches cases.data.mjs labeledCells ids). Decoys resolve
// to a NON-culprit value (the "obvious" suspect the misdirection points at).
const CONFIGS = [
  { key: 'case1', seed: 1101, culprit: 3, labeled: [{ box: 1, id: 'landing' }, { box: 7, id: 'expose' }], sceneBox: 4, decoys: [] },
  { key: 'case2', seed: 2202, culprit: 6, labeled: [{ box: 4, id: 'sidedoor' }, { box: 6, id: 'club' }], sceneBox: 2, decoys: [] },
  { key: 'case3', seed: 3303, culprit: 8, labeled: [{ box: 3, id: 'ledger' }, { box: 5, id: 'key' }], sceneBox: 8,
    decoys: [{ box: 1, id: 'quarrel', value: 2 }] },
];

const GRIDS = {};
for (const cfg of CONFIGS) {
  const g = buildCaseGrid({
    seed: cfg.seed, culprit: cfg.culprit,
    labeledBoxes: cfg.labeled.map((l) => l.box), sceneBox: cfg.sceneBox, decoys: cfg.decoys,
    targetBlanks: 55, minTech: 'locked-candidates', maxTech: 'naked-pair', maxTries: 4000,
  });
  // map box -> id for the labeled cells
  const cells = {};
  for (const l of cfg.labeled) cells[l.id] = g.labeledCells[l.box];
  for (const d of cfg.decoys) cells[d.id] = g.decoyCells[d.id];
  GRIDS[cfg.key] = {
    solution: g.solution, givens: g.givens, murderCell: g.sceneCell, sceneBox: cfg.sceneBox, cells,
  };
  const rating = rateDifficulty(g.givens);
  console.log(`\n=== ${cfg.key} (seed ${cfg.seed}, culprit ${cfg.culprit}) ===`);
  console.log(`givens ${g.givens.filter((v) => v).length}  blanks ${g.givens.filter((v) => !v).length}  tries ${g.tries}  unique ${hasUniqueSolution(g.givens)}  hardest=${rating.hardest} solved=${rating.solved}`);
  console.log(`scene ${g.sceneCell}=${rc(g.sceneCell)} val ${g.solution[g.sceneCell]}`);
  for (const l of cfg.labeled) console.log(`  ${l.id}: cell ${cells[l.id]}=${rc(cells[l.id])} val ${g.solution[cells[l.id]]}`);
  for (const d of cfg.decoys) console.log(`  decoy ${d.id}: cell ${cells[d.id]}=${rc(cells[d.id])} val ${g.solution[cells[d.id]]} (culprit is ${cfg.culprit})`);
}

// Write the grids module.
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const body = `// GENERATED by tools/gen-grids.mjs — do not edit by hand. Hard, unique, logic-solvable
// grids for the detective cases. cases.data.mjs imports these; verify-cases.mjs re-proves them.
export const GRIDS = ${JSON.stringify(GRIDS, null, 0)};
export default GRIDS;
`;
writeFileSync(join(ROOT, 'tools', 'cases.grids.mjs'), body);
console.log('\nWrote tools/cases.grids.mjs');
